env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - '*.js'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-magic-numbers: error
  no-var: error
  quotes:
    - error
    - double
  semi:
    - error
    - always
